### ISSUE TITLE
Please update to nodejs8.10

### ISSUE THREAD

**Issue by r2ad** [alestic/lambdash#9]
The current version of node in the template is no longer supported.  So just update to nodejs8.10.  Tested this and it works well.  
Thanks!!

**Comment by ehammond** [comment]
@r2ad Thank you!

I'm not sure how soon I'll get around to taking care of this, but if somebody wants to submit a PR, I'll review.

Having a second person test and say it worked would also speed things up.

**Comment by ruurtjan** [comment]
Here's a PR @ehammond, @r2ad: https://github.com/alestic/lambdash/pull/8

**Comment by ehammond** [comment]
Thanks. Merged!
